# Lab 1: Warmup

## Environment check

Run the following cell to check that your environment is set up properly.

In [6]:
import torch

# FIXME: check 'pip' path
pip_path = !which pip
assert 'conda' in pip_path[0], "pip path should include conda"

In [5]:
x = !which python
x

['/usr/local/Caskroom/miniconda/base/bin/python']

In [2]:
x

['/usr/local/Caskroom/miniconda/base/bin/pip']

## Jupyter Notebooks

Add your code and Markdown cells here. Delete this cell.

## NumPy

In [9]:
import numpy as np

### Broadcasting and Aggregation

In [49]:
y_true = np.array([3.1, 4.1, 5.9])
y_pred = np.array([2.1, 3.1, 6.9])

Compute the residual (error) as true minus predicted. Assign the result to `resid`. **Note: no loop needed!**

Add a line at the end of the cell containing just `resid`. The last expression in any cell gets displayed.

In [50]:
resid = y_true - y_pred
resid

array([ 1.,  1., -1.])

Compute the squared error by raising `resid` to the power 2. (Recall that Python's exponentiation operator is `**`.) Assign this to `squared_error` and display it.

In [51]:
squared_error = resid ** 2
squared_error

array([1., 1., 1.])

Compute the mean of the squared error. Try two different ways: `squared_error.mean()` and `np.mean(squared_error)`.

In [52]:
squared_error.mean()

0.9999999999999997

In [18]:
np.mean(squared_error)

0.009999999999999959

Now, try to write the entire computation in a single succinct expression

In [19]:
np.mean((y_true - y_pred) ** 2)

0.009999999999999959

### Dot products

Recall that we can make a line by an expression like `y = w*x + b`. (Some of you may remember *mx+b* , but we'll use *w* for the *weight(s)* instead.)

That's a multiplication followed by a sum. We can extend that to lots of *x*'s, each of which needs a corresponding *w*:

`y = w1*x1 + w2*x2 + ... + b`

Let's do that in NumPy. 

In [20]:
x = np.array([1.5, 2.0])
x

array([1.5, 2. ])

In [21]:
w = np.array([-2.0, 1.0])
w

array([-2.,  1.])

In [22]:
w * x

array([-3.,  2.])

In [23]:
np.sum(w * x)

-1.0

In [24]:
np.dot(w, x)

-1.0

In [26]:
w @ x

-1.0

## Functions

Write a function that performs the `w*x + b` computation we just did:

In [27]:
def linear(weights, bias, x):
    return weights @ x + bias
linear(w, 1.0, x)

0.0

However, it would be convenient to view the `linear` function as simply a function of `x`, with `weights` and `bias` being internal details. There are several ways to do this; perhaps most familiar to you might be to make a `Linear` class that has these as paramaters. Fill in the blanks here:

In [28]:
class Linear:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def forward(self, x):
        return self.weights @ x + self.bias

layer = Linear(w, 1.0)
layer.forward(x)

0.0

But there's another view that you should also get comfortable with: a function can simply return a function.

In [30]:
def make_multiplier(x):
    def multiply_by(y):
        return x * y
    return multiply_by
make_multiplier(5)(2)

10

Use this pattern to make a `make_projector`:

In [33]:
def make_projector(weights, bias):
    def forward(x):
        return weights @ x + bias
    return forward
make_projector(w, 1.0)(x)

0.0

*Supplemental Notes (optional)*:

- The inner function is called a *closure*.
- This programming pattern is used quite frequently in user interface programming, e.g,. JavaScript.
- Here we only used it for "partial application"; we could have instead used `functools.partial(f, weights = w, bias = 1.0)`.
- We'll use this later for implementing backpropagation.
