<a href="https://colab.research.google.com/github/kcarnold/cs344/blob/main/src/Number_of_Dimensions_is_not_Rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
t1 = torch.ones((5, 1)); t1

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [4]:
t2 = torch.ones((1, 4)); t2

tensor([[1., 1., 1., 1.]])

In [6]:
t3 = t1 @ t2; t3

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
t3.shape

torch.Size([5, 4])

In [9]:
t3.ndim

2

In [7]:
torch.matrix_rank(t3)

tensor(1)